### ISSUE TITLE
[PROBLEM]Error when install the addon

### ISSUE THREAD

**Issue by automataIA** [Kos-Design/substance_textures_importer#1]
give this error:
![immagine](https://user-images.githubusercontent.com/53933533/85420819-fe44a700-b573-11ea-9bf4-4960b8ed2078.png)

**Comment by Kos-Design** [comment]
Thanks for the report, I fixed it (github renamed the folder). 
Please use this archive instead to install the plugin : 
https://github.com/Kos-Design/materials_substance/raw/master/Blender_Substance_Texture_Importer.zip
