### ISSUE TITLE
blender  crash easily

### ISSUE THREAD

**Issue by infernoshoot** [Kos-Design/substance_textures_importer#2]
blender  crash easily

**Comment by Kos-Design** [comment]
Hi  thanks for the bugreport, are you using cycles or Evee when importing the textures ? 
(sometimes Evee doesn't like if there are too many large textures to display at once,, try using Cycles, at least during the texture, import as a workaround)

**Comment by Kos-Design** [comment]
Please let me know if you find a way to reproduce your issue in case it persists.
